### PR TITLE
Add a script for GPU benchmarks

### PR DESCRIPTION
**Pull request by DilumAluthge**
I've been playing around with trying to do some BLAS benchmarks on GPU as well. Nothing too noteworthy - cuBLAS absolutely clobbers Tullio.

Not sure where the code for this should go. Would GPU benchmarking be within the scope of this repo?

### CODE REVIEW

**Comment by chriselrod** [comment]
That'd probably have been okay, but separate repos is fine too.

**Comment by DilumAluthge** [comment]
Since right now it's mainly just Tullio vs cuBLAS, I'm going to:
1. Run the benchmarks
2. See if it's worth adding the script to Tullio.jl

**Comment by DilumAluthge** [comment]
There aren't really a lot of options for pure-Julia GEMM that is competitive with cuBLAS.

I'm looking at https://github.com/thomasfaingnaert/GemmKernels.jl right now.

**Comment by chriselrod** [comment]
They show some impressive performance! Definitely seems worth adding GemmKernels to a GPU library.

I don't even own an NVidea GPU, but I could do ROCm (AMD, Vega GPU) or oneAPI (Intel Xe integrated graphics).

**Pull request closed without merging**
